domains:
  - domain: '{{ app }}.{{ branch }}.{{ environment }}.parallax.dev'
    environments: '*'
    branches: '*'
  - domain: '{{ app }}.{{ environment }}.parallax.dev'
    environments: '*'
    branches: 'master'
aws:
  s3:
  databases:
  - type: 'mysql57'
afterDeploy:
  delete:
    - kind: Deployment
      namePattern: '{{ app }}-{{ branch }}-*'
      nameApartFrom: '{{ app }}-{{ branch }}-{{ build }}'
      namespace: '{{ namespace }}'