stage: 4
apiVersion: v1
kind: Service
metadata:
  name: '{{ branch }}-metabase'
  namespace: '{{ namespace }}'
spec:
  ports:
  - name: metabase
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: '{{ app }}-{{ branch }}-{{ build }}'
  sessionAffinity: None
  type: ClusterIP